app/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path, include
from app import views

urlpatterns = [
    # The home page
    #path('', views.applications, name='home'),
    path('', views.list_noti, name='home'),
    path('create', views.join, name='join'),
    path('postn', views.post_noti, name='post_noti'),
    path('postl', views.list_noti, name='list_noti'),
    path('postp/<int:postnum>/',views.page_noti, name='page_noti'),
    path('join', views.joinpage, name="page_join"),
    path('ulogin', views.ulogin, name="ulogin"),
    path('submit', views.app_submit, name="app_submit"),

    path('export', views.export, name="export"),

    path('applications', views.applications, name="app_list"), #내공모
    path('users',views.list_user,name='list_user'),

    path('apply', views.post_submit, name="post_submit"),
    path('update/<int:aid>/',views.update_application, name="app_update"),

    path('appdetail/<int:aid>/',views.app_detail, name="app_detail"),
    path('confirm/<int:aid>/',views.confirm, name="confirm"),

    path('noti_delete/<int:nid>/', views.delete_noti, name="delte_noti"),


    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),
] 

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]

app/forms.py
from django import forms
from django.forms import CharField as C
from django.forms import IntegerField as I

class NotificationForm(forms.Form):
    title = C(max_length=300)
    content = C(max_length=7000)

class ApplicantForm(forms.Form):
    uid = forms.CharField(label='uid', max_length=200,required=True)
    password = forms.CharField(label='password', max_length=200,required=True)
    password_check = forms.CharField(label='password_check', max_length=200,required=True)
    
    name = C(label='name',max_length=100)
    email = C(label='email',max_length=100)

    contact = C(label='contact',max_length=100)

    applicant_type = C(label='applicant_type', max_length=20)
    applicant_agree_yn = C(label='applicant_type', max_length=20)

class ApplicationForm(forms.Form):
    app_type = C(label="app_type",max_length=20)
    
    isbn = C(label='isbn',max_length=30)
    book_title = C(label='book_title',max_length=300)
    
    author_name = C(label='author_name',max_length=200)
    publisher_name = C(label='publisher_name',max_length=200)
    
    publish_1st_date = C(label='publish_date',max_length=100)

    price = C(label='price')

    book_width = C(label='width')
    book_height = C(label='height')
    book_page_cnt = C(label='page_num')
    
    book_detail = C(label='book_detail',max_length=3000)
    author_detail = C(label='author_detail', max_length=3000)

    publisher_detail =  C(label='author_detail', max_length=3000)
    

core/templates/board.html
{% extends 'layouts/base.html' %}

{% block title %} Notice Board {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" 
         style="min-height: 100px; background-image: url(/static/assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-8"></span>
      <!-- Header container -->
    </div>

    <div class="container-fluid mt--7">

      <div class="row">
        <div class="col-xl-12 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">My account</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="#!" class="btn btn-sm btn-primary">Settings</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form>
                <h6 class="heading-small text-muted mb-4">User information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">Username</label>
                        <input type="text" id="input-username" class="form-control form-control-alternative" placeholder="Username" 
                               value="{{ request.user.username }}">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Email address</label>
                        <input type="email" id="input-email" class="form-control form-control-alternative" 
                               placeholder="{{ request.user.email }}">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">First name</label>
                        <input type="text" id="input-first-name" class="form-control form-control-alternative" >
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Last name</label>
                        <input type="text" id="input-last-name" class="form-control form-control-alternative" >
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4" />
                <!-- Address -->
                <h6 class="heading-small text-muted mb-4">Contact information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-address">Address</label>
                        <input id="input-address" class="form-control form-control-alternative" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" type="text">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-city">City</label>
                        <input type="text" id="input-city" class="form-control form-control-alternative" placeholder="City" value="New York">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Country</label>
                        <input type="text" id="input-country" class="form-control form-control-alternative" placeholder="Country" value="United States">
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Postal code</label>
                        <input type="number" id="input-postal-code" class="form-control form-control-alternative" placeholder="Postal code">
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4" />
                <!-- Description -->
                <h6 class="heading-small text-muted mb-4">About me</h6>
                <div class="pl-lg-4">
                  <div class="form-group">
                    <label>About Me</label>
                    <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/join.html
{% extends 'layouts/base.html' %}

{% block title %} 회원가입 {% endblock title %}

{% block content %}

    <!-- Header -->

    <div class="container-fluid mt--7">
      
      <div class="row">
        <div class="col-xl-12 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">회원가입</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="javascript:document.applicant.submit();" class="btn btn-sm btn-primary">가입</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <div>
                공모전 회원가입 안내문구 
롯데출판문화대상 공모전 참여를 위한 간편회원가입 페이지입니다.
비밀번호가 암호화 되지 않으므로 쉽게 노출되지 않는 개인식별 가능한 숫자 6자리를 이용하여 가입완료 바랍니다.
              </div>
                <form name="applicant" method="post" action="create" >{% csrf_token %}
                <h2 style="color:crimson">{{ error_msg }}</h2>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group" >
                          <label class="form-control-label" for="id_uid" >ID {{no_uid}}</label>
                        <input type="text" id="uid" name="uid" value="{{old_uid}}" class="form-control form-control-alternative" >
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group" >
                          <label class="form-control-label" for="id_uid" >이름(출판사명) {{no_name}}</label>
                        <input type="text" id="uid" name="name" value="{{old_name}}" class="form-control form-control-alternative" >
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                          <label class="form-control-label" for="input-username">비밀번호(숫자만입력) {{not_eq}}</label>
                        <input type="text" name="password" class="form-control form-control-alternative" value="" onkeypress="onlyNumber();">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">비밀번호 확인</label>
                        <input type="text" name="password_check" class="form-control form-control-alternative" onkeypress="onlyNumber();">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                          <label class="form-control-label" for="input-first-name">연락처 {{no_contact}}</label>
                          <input type="text" name="contact" value="{{old_contact}}" class="form-control form-control-alternative" >
                      </div>
                    </div>
                </div>
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                        <label class="form-control-label" for="input-username">이메일 {{no_email}} </label>
                        <input type="text" name="email" class="form-control form-control-alternative" value="{{old_email}}">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <label class="form-control-label" for="input-username">지원자 구분</label>
                      <div class="col-lg-6">
                          <div class="row">
                            <input type="radio" name="applicant_type" value='a' checked="">
                            <label >공모전 참여도서의 원저작자(번역자)입니다. </label>
                          </div>
                          <div class="row">
                            <input type="radio" name="applicant_type" value='p'>
                            <label >저작자[번역자]와 협의를 거쳐 출판사 대표가 응모 함.</label>
                          </div>
                      </div>
                            <label >※ 협의되지 않았거나 분쟁이 발생 할 경우 모든 책임은 출판사 대표에게 있음을 확인합니다.</label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-10">
                    <div class="form-group">
                      <textarea style="width: 100%;" rows="20" class="form-control form-control-alternative" >
개인정보보호법 제15조 법규에 의거하여 롯데재단은 제4회 롯데출판문화대상 공모 참여자에 대한 개인정보 수집 및 활용과 행사 수행기관의 제3자에 대한 개인정보 이용 및 활용 동의서를 받고 있습니다.
다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 개인정보보호법 제18조에 따라 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다
롯데재단에서는 원활한 개인정보 업무처리를 위하여 다음과 같이 개인정보 처리업무를 위탁하고 있습니다. 
 -운영대행 : 한국전자출판학회   / -접수대행 : 한국출판협동조합

제공된 개인정보의 이용을 거부하고자 할 때에는 개인정보 관리책임자를 통해 열람, 정정 혹은 삭제를 요구할 수 있습니다.
(단, 개인정보 이용의 제한 시 공모전 접수처리가 불가합니다.)

※ 제공된 개인정보는 아래 항목에 제한된 범위에서만 활용됩니다.

개인정보수집 및 이용목적	

【개인정보 수집 항목】

  공모전 접수 관련 세부 정보
 - 개  인 : 성명, 주소, 사업자번호, 전화번호, 이메일 등
 - 업  체 : 업체명, 사업자번호, 주소, 전화번호, 업체현황 등
 - 공모작 : 도서명, 저자명, 공모관련 제공정보  등 

【개인정보 활용 및 제3자 이용의 목적】

- 공모전 관련 일체 : 공모접수 및 공모심사 활용
- 제3자 이용 목적 : 
  1) 공모전 접수 및 요청자의 동의 상담 답변
  2) 공모전 접수 현황 등의 안내

기타 공모전 진행관련 협조
                      </textarea>
                    </div>
                  </div>
                </div>

                 상기 내용을 확인하였으며, 확인 사항에  동의합니다.
                 <a href="javascript:document.applicant.submit();" class="btn btn-sm btn-primary">가입</a>

                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>
    <script>
    function onlyNumber(){
        if((event.keyCode<48)||(event.keyCode>57))
            event.returnValue=false;
    }
    </script>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/maps.html
{% extends 'layouts/base.html' %}

{% block title %} Maps {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
      <div class="container-fluid">
        <div class="header-body">
          <!-- Card stats -->
          <div class="row">
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Traffic</h5>
                      <span class="h2 font-weight-bold mb-0">350,897</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                        <i class="fas fa-chart-bar"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span class="text-nowrap">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">New users</h5>
                      <span class="h2 font-weight-bold mb-0">2,356</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                        <i class="fas fa-chart-pie"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-danger mr-2"><i class="fas fa-arrow-down"></i> 3.48%</span>
                    <span class="text-nowrap">Since last week</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Sales</h5>
                      <span class="h2 font-weight-bold mb-0">924</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                        <i class="fas fa-users"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-warning mr-2"><i class="fas fa-arrow-down"></i> 1.10%</span>
                    <span class="text-nowrap">Since yesterday</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-lg-6">
              <div class="card card-stats mb-4 mb-xl-0">
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0">Performance</h5>
                      <span class="h2 font-weight-bold mb-0">49,65%</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-info text-white rounded-circle shadow">
                        <i class="fas fa-percent"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-muted text-sm">
                    <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 12%</span>
                    <span class="text-nowrap">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt--7">

      <div class="row">
        <div class="col">
          <div class="card shadow border-0">
            <div id="map-canvas" class="map-canvas" data-lat="40.748817" data-lng="-73.985428" style="height: 600px;"></div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/notifications.html
{% extends 'layouts/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

    <!-- Header -->
    <meta property="og:image" content="/static/assets/img/banner.jpg" />
    <div class="header pb-4 pt-5 pt-md-8"
         style="min-height: 100px; background-image: url(/static/assets/img/banner.jpg); background-size: cover; background-position: center top;">
      <div class="container-fluid">
      </div>
    </div>

    <div class="container-fluid mt--7">

      <!-- Table -->
      <div class="row">
        <div class="col">
          <div class="card shadow">
            <div class="card-header border-0">
              <h3 class="mb-0">공지사항</h3>
            </div>
            <div class="table-responsive">
              {% if is_admin %}
              <a href="/notify.html" class="btn btn-smbtn-primary" >글등록</a>
              {% endif %}
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">제목</th>
                    <th scope="col">작성자</th>
                    <th scope="col"></th>
                    <th scope="col">등록일시</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for noti in notis %}
                  <tr onClick="location.href='/postp/{{noti.nid}}/'">
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                          <img alt="Image placeholder" src="/static/assets/img/theme/bootstrap.jpg">
                        </a>
                        <div class="media-body">
                            <span class="mb-0 text-sm">{{ noti.title }}</span>
                        </div>
                      </div>
                    </th>
                    <td>
                        관리자
                    </td>
                    <td>
                      <span class="badge badge-dot mr-4">
                      </span>
                    </td>
                    <td>{{noti.created_at}}</td>
                    <td>
                      <div class="d-flex align-items-center">
                        <div>
                          {% if is_admin %}
                            <a href="/noti_delete/{{noti.nid}}/" class="btn btn-sm btn-primary">삭제</a>
                          {% else %}
                            here
                          {% endif %}
                        </div>
                      </div>
                    </td>
                    <td class="text-right">
                      <div class="dropdown">
                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fas fa-ellipsis-v"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- Dark table -->
      {% include "includes/footer.html" %}
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/notify.html
{% extends 'layouts/base.html' %}

{% block title %} 회원가입 {% endblock title %}

{% block content %}

    <!-- Header -->

    <div class="container-fluid mt--7">
      

      <div class="row">
        <div class="col-xl-12 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">회원가입</h3>
                </div>
                <div class="col-4 text-right">
                  <a href="javascript:document.applicant.submit();" class="btn btn-sm btn-primary">가입</a>
                </div>
              </div>
            </div>
            <div class="card-body">
                <form id="notify" name="notification_form" method="post" action="postn" >{% csrf_token %}
                <h6 class="heading-small text-muted mb-4">User information</h6>
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-12 row-lg-4" >
                      <div class="form-group" >
                          <label class="form-control-label" for="id_uid" >공지 제목 {{no_uid}}</label>
                        <input type="text" id="title" name="title" value="{{old_uid}}" class="form-control form-control-alternative" >
                      </div>
                    </div>
                    <div class="col-lg-12" style="height: 340px" id="editor"> </div>
                  </div>
                </div>
              </form>
                  <a href="javascript:submit_func();" class="btn btn-sm btn-primary">작성</a>
            </div>
          </div>
        </div>
      </div>

      {% include "includes/footer.html" %}

    </div>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="//cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <script>
    var quill = new Quill('#editor', {
        modules: {
        toolbar: [
            [{ header: [1, 2, false] }],
            ['bold', 'italic', 'underline'],
            ['code-block']
            ]
        },
        placeholder: 'Compose an epic...',
        theme: 'snow'
    });

    function post(path, params, method='post') {

                  // The rest of this code assumes you are not using a library.
                  // It can be made less verbose if you use one.
                  const form = document.createElement('form');
                  form.method = method;
                  form.action = path;

                  for (const key in params) {
                          if (params.hasOwnProperty(key)) {
                                    const hiddenField = document.createElement('input');
                                    hiddenField.type = 'hidden';
                                    hiddenField.name = key;
                                    hiddenField.value = params[key];
                                    form.appendChild(hiddenField);
                                  }
                        }

                  document.body.appendChild(form);
                  form.submit();
    }


    function submit_func() {
        var html = quill.root.innerHTML;
        var title = document.getElementById("title");
        $("#title").append("<textarea name='content' style='display:none'>"+html+"</textarea>");
        $("#notify").submit();
    }

    </script>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/notipage.html
{% extends 'layouts/base2.html' %}

{% block title %} 회원가입 {% endblock title %}

{% block content %}

    <!-- Header -->
    <div class="container-fluid mt--7">

      <div class="row">
        <div class="col-xl-12 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">회원가입</h3>
                </div>
                <div class="col-4 text-right">
                </div>
              </div>
            </div>
            <div class="card-body">
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-12">
                      <div class="form-group" >
                        <label class="form-control-label" for="id_uid" >{{no_uid}}</label>
                        <input type="text" id="uid" name="uid" value="{{noti.title}}" class="form-control form-control-alternative" >
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-12">
                        {{ noti.content |safe }}
                    </div>
                  </div>
                </div>
              <a href="/" class="btn">목록으로</a>
          </div>
      </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 

core/templates/page-403.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 403      
              </div>

              <div class="text-center mb-4">
                Access denied - Contact support or <a href="{% url 'login' %}"><small>AUTHENTICATE</small></a>.
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="{% url 'login' %}" class="text-light"><small>LOGIN</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

core/templates/page-404.html
{% extends 'layouts/base-fullscreen.html' %}

{% block title %} Error 404 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Page content -->
    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="card bg-secondary shadow border-0">
            <div class="card-header bg-transparent pb-5">

              <div class="text-muted text-center mt-2 mb-3">
                Oups! Error 404      
              </div>

              <div class="text-center mb-4">
                Page not found - <a href="/">Home</a>
              </div>

            </div>
          </div>
          <div class="row mt-3">
            <div class="col-6">
              <a href="/" class="text-light"><small>Home</small></a>
            </div>
            <div class="col-6 text-right">
              <a href="https://appseed.us/support" class="text-light"><small>Get Support</small></a>
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}